version: '3.4'

services:
  carracingteam.api:
    image: ${DOCKER_REGISTRY-}carracingteamapi
    build:
      context: .
      dockerfile: src/Apis/CarRacingTeam/src/CarRacingTeam.Api/Dockerfile

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

